# Generated by Django 3.2.4 on 2021-12-01 12:50

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0042_score_coin_models_score_coin_editable_false'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, verbose_name='اسلاگ')),
                ('short_description', models.CharField(max_length=255, verbose_name='توضیح کوتاه')),
                ('full_description', models.TextField(verbose_name='توضیح کامل')),
                ('deadline_duration', models.DurationField(blank=True, null=True, verbose_name='مدت زمان تحویل')),
                ('waiting_duration', models.DurationField(blank=True, default=datetime.timedelta(seconds=60), help_text='زمان انتظار برای تحویل این آزمون پس از اتمام', null=True, verbose_name='زمان انتظار')),
                ('starts_at', models.DateTimeField(null=True, verbose_name='زمان شروع')),
                ('ends_at', models.DateTimeField(null=True, verbose_name='زمان پایان')),
                ('coin_cost', models.PositiveIntegerField(verbose_name='قیمت به سکه')),
                ('diamond_cost', models.PositiveIntegerField(verbose_name='قیمت به الماس')),
                ('correct_score', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='امتیاز جواب صحیح')),
                ('blank_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)], verbose_name='امتیاز نزده')),
                ('incorrect_score', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='امتیاز جواب غلط')),
                ('correct_coin', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='سکه جواب صحیح')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default/exam/exam-image.png', force_format='JPEG', keep_meta=True, quality=72, size=[960, 540], upload_to='images/exam_thumbnails', verbose_name='تصویر')),
                ('confirm_status', models.IntegerField(choices=[(0, 'در انتظار تایید'), (1, 'تایید شده'), (-1, 'رد شده')], default=0, verbose_name='وضعیت تایید')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('categories', models.ManyToManyField(related_name='exams', to='learning.Category', verbose_name='دسته بندی ها')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='طراح آزمون')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون ها',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
