# Generated by Django 3.2.4 on 2021-12-01 13:36

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=500, verbose_name='متن سوال')),
                ('choice_1', models.CharField(max_length=100, verbose_name='گزینه اول')),
                ('choice_2', models.CharField(max_length=100, verbose_name='گزینه دوم')),
                ('choice_3', models.CharField(max_length=100, verbose_name='گزینه سوم')),
                ('choice_4', models.CharField(max_length=100, verbose_name='گزینه چهارم')),
                ('correct_choice', models.IntegerField(choices=[(1, 'گزینه 1'), (2, 'گزینه 2'), (3, 'گزینه 3'), (4, 'گزینه 4')], help_text='پاسخ پس از اتمام زمان آزمون برای دانش آموز نمایش داده می شود', verbose_name='جواب صحیح')),
                ('correct_full_answer', models.TextField(help_text='پاسخ پس از اتمام زمان آزمون برای دانش آموز نمایش داده می شود', max_length=1000, verbose_name='پاسخ تشریحی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
