# Generated by Django 3.2.4 on 2021-12-05 13:00

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_answer', models.IntegerField(choices=[(1, 'گزینه 1'), (2, 'گزینه 2'), (3, 'گزینه 3'), (4, 'گزینه 4')], null=True)),
                ('correct_answer', models.IntegerField(choices=[(1, 'گزینه 1'), (2, 'گزینه 2'), (3, 'گزینه 3'), (4, 'گزینه 4')])),
                ('answer_status', models.IntegerField(choices=[(1, 'صحیح'), (-1, 'غلط'), (0, 'نزده')])),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.examresult')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.question')),
            ],
            options={
                'verbose_name': 'پاسخ کاربر',
                'verbose_name_plural': 'پاسخ\u200cهای کاربران',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='examresult',
            name='questions',
            field=models.ManyToManyField(related_name='exam_results', through='exam.ParticipantAnswer', to='exam.Question'),
        ),
    ]
