# Generated by Django 3.2.4 on 2021-12-13 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0004_participant_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='likers',
            field=models.ManyToManyField(related_name='liked_exams', to=settings.AUTH_USER_MODEL, verbose_name='کاربران لایک کرده'),
        ),
        migrations.AlterField(
            model_name='participantanswer',
            name='answer_status',
            field=models.IntegerField(choices=[(1, 'صحیح'), (-1, 'غلط'), (0, 'نزده')], default=0),
        ),
        migrations.CreateModel(
            name='ExamLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, editable=False, verbose_name='امتیاز')),
                ('coin', models.IntegerField(default=0, editable=False, verbose_name='سکه')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='exam.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لایک آزمون',
                'verbose_name_plural': 'لایک آزمون ها',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
