# Generated by Django 3.2.4 on 2021-12-21 20:47

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_exam_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='full_description',
            field=django_bleach.models.BleachField(verbose_name='توضیح کامل'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='short_description',
            field=django_bleach.models.BleachField(max_length=255, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_1',
            field=django_bleach.models.BleachField(max_length=100, verbose_name='گزینه اول'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_2',
            field=django_bleach.models.BleachField(max_length=100, verbose_name='گزینه دوم'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_3',
            field=django_bleach.models.BleachField(max_length=100, verbose_name='گزینه سوم'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_4',
            field=django_bleach.models.BleachField(max_length=100, verbose_name='گزینه چهارم'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_full_answer',
            field=django_bleach.models.BleachField(help_text='پاسخ پس از اتمام زمان آزمون برای دانش آموز نمایش داده می شود', max_length=1000, verbose_name='پاسخ تشریحی'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=django_bleach.models.BleachField(max_length=500, verbose_name='متن سوال'),
        ),
    ]
