# Generated by Django 3.2.4 on 2021-12-21 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0006_textfield_to_bleachfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='participants',
            field=models.ManyToManyField(related_name='participated_exams', through='exam.ExamResult', to=settings.AUTH_USER_MODEL, verbose_name='شرکت کنندگان'),
        ),
    ]
