# Generated by Django 3.2.4 on 2022-01-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_exam_model_participants_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='status',
        ),
        migrations.AddField(
            model_name='examresult',
            name='mark_status',
            field=models.IntegerField(choices=[(1, 'پردازش شروع نشده'), (2, 'در حال پردازش'), (3, 'پردازش تمام شده')], default=1, verbose_name='وضعیت کارنامه'),
        ),
    ]
