# Generated by Django 4.0 on 2022-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_rename_exam_result_participantanswer_exam_participation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantanswer',
            name='correct_answer',
            field=models.IntegerField(choices=[(1, 'گزینه 1'), (2, 'گزینه 2'), (3, 'گزینه 3'), (4, 'گزینه 4')], null=True),
        ),
    ]
