# Generated by Django 4.0.2 on 2022-02-03 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_participant_answer_correct_answer_became_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examparticipation',
            name='score_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد امتیاز'),
        ),
    ]
