# Generated by Django 4.0.2 on 2022-02-09 09:10

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0011_exam_participation_score_percent_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='deadline_duration',
            field=models.DurationField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60))], verbose_name='مدت زمان تحویل'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='designer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='طراح آزمون'),
        ),
        migrations.AlterField(
            model_name='examparticipation',
            name='exam',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam.exam', verbose_name='آزمون'),
        ),
        migrations.AlterField(
            model_name='examparticipation',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='شروع شده در'),
        ),
        migrations.AlterField(
            model_name='examparticipation',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='exam_participations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='participantanswer',
            name='exam_participation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.examparticipation'),
        ),
        migrations.AlterField(
            model_name='participantanswer',
            name='question',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exam'),
        ),
        migrations.AlterUniqueTogether(
            name='examlike',
            unique_together={('user', 'exam')},
        ),
    ]
