# Generated by Django 3.1.7 on 2021-03-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='images/avatars', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.PositiveIntegerField(verbose_name='سکه ها'),
        ),
        migrations.AlterField(
            model_name='user',
            name='diamonds',
            field=models.PositiveIntegerField(verbose_name='الماس ها'),
        ),
        migrations.AlterField(
            model_name='user',
            name='scores',
            field=models.PositiveIntegerField(verbose_name='امتیاز'),
        ),
    ]
