# Generated by Django 3.1.7 on 2021-04-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_integer_fields_set_default_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default/authentication/user-avatar.png', upload_to='images/avatars', verbose_name='تصویر پروفایل'),
        ),
    ]
