# Generated by Django 3.2.2 on 2021-05-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_autofield_bigautofield"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (("email_confirmed", "ایمیل تایید شده"),),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="email_confirmed",
            field=models.BooleanField(
                default=False, verbose_name="تایید ایمیل"
            ),
        ),
    ]
