# Generated by Django 3.2.4 on 2021-06-13 13:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default/authentication/user-avatar.png', force_format='JPEG', keep_meta=True, quality=72, size=[300, 300], upload_to='images/avatars', verbose_name='تصویر پروفایل'),
        ),
    ]
