# Generated by Django 3.1.7 on 2021-03-26 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_grades', to='learning.category', verbose_name='پایه والد')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='اسلاگ')),
                ('short_description', models.CharField(max_length=250, verbose_name='توضیح کوتاه')),
                ('body', models.TextField(verbose_name='بدنه')),
                ('total_views_count', models.PositiveIntegerField(verbose_name='بازدید کل')),
                ('user_views_count', models.PositiveIntegerField(verbose_name='بازدید کاربران')),
                ('up_votes_count', models.PositiveIntegerField(verbose_name='امتیاز مثبت')),
                ('down_votes_count', models.PositiveIntegerField(verbose_name='امتیاز منفی')),
                ('likes_count', models.PositiveIntegerField(verbose_name='لایک ها')),
                ('image', models.ImageField(blank=True, upload_to='images/tutorial_thumbnails', verbose_name='تصویر')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('last_edit_date', models.DateField(auto_now=True, verbose_name='زمان آخرین ویرایش')),
                ('confirm_status', models.IntegerField(choices=[(-1, 'عدم تایید'), (0, 'در انتظار تایید'), (1, 'تایید شده')], verbose_name='وضعیت تایید')),
                ('is_edited', models.BooleanField(default=True, verbose_name='ویرایش شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorials', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('categories', models.ManyToManyField(related_name='tutorials', to='learning.Category', verbose_name='دسته بندی ها')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='امتیاز')),
                ('coin', models.PositiveIntegerField(verbose_name='سکه')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.tutorial', verbose_name='آموزش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialUpVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='امتیاز')),
                ('coin', models.PositiveIntegerField(verbose_name='سکه')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.tutorial', verbose_name='آموزش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slugs', to='learning.tutorial', verbose_name='آموزش')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='امتیاز')),
                ('coin', models.PositiveIntegerField(verbose_name='سکه')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.tutorial', verbose_name='آموزش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialDownVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='امتیاز')),
                ('coin', models.PositiveIntegerField(verbose_name='سکه')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.tutorial', verbose_name='آموزش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('body', models.TextField(max_length=500, verbose_name='بدنه')),
                ('up_votes', models.PositiveIntegerField(verbose_name='امتیاز مثبت')),
                ('down_votes', models.PositiveIntegerField(verbose_name='امتیاز منفی')),
                ('likes', models.PositiveIntegerField(verbose_name='لایک ها')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('last_edit_date', models.DateField(auto_now=True, verbose_name='زمان آخرین ویرایش')),
                ('confirm_status', models.IntegerField(choices=[(-1, 'عدم تایید'), (0, 'در انتظار تایید'), (1, 'تایید شده')], verbose_name='وضعیت تایید')),
                ('is_edited', models.BooleanField(default=True, verbose_name='ویرایش شده')),
                ('allow_reply', models.BooleanField(default=True, verbose_name='امکان پاسخ')),
                ('notify_replies', models.BooleanField(default=True, verbose_name='اطلاع رسانی پاسخ ها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_comments', to='learning.tutorialcomment', verbose_name='پاسخ به')),
                ('tutorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.tutorial', verbose_name='آموزش')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.AddField(
            model_name='tutorial',
            name='comments',
            field=models.ManyToManyField(related_name='tutorial_comments', through='learning.TutorialComment', to=settings.AUTH_USER_MODEL, verbose_name='نظرات'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='down_votes',
            field=models.ManyToManyField(related_name='tutorial_down_votes', through='learning.TutorialDownVote', to=settings.AUTH_USER_MODEL, verbose_name='امتیاز های منفی'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='likes',
            field=models.ManyToManyField(related_name='tutorial_likes', through='learning.TutorialLike', to=settings.AUTH_USER_MODEL, verbose_name='لایک ها'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='up_votes',
            field=models.ManyToManyField(related_name='tutorial_up_votes', through='learning.TutorialUpVote', to=settings.AUTH_USER_MODEL, verbose_name='امتیاز های مثبت'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='views',
            field=models.ManyToManyField(related_name='tutorial_views', through='learning.TutorialView', to=settings.AUTH_USER_MODEL, verbose_name='بازدید ها'),
        ),
    ]
