# Generated by Django 3.1.7 on 2021-03-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_tutotial_category_tutorialcomment_verbose_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='tutorial',
            options={'verbose_name': 'آموزش', 'verbose_name_plural': 'آموزش ها'},
        ),
        migrations.AlterModelOptions(
            name='tutorialcomment',
            options={'verbose_name': 'دیدگاه آموزش', 'verbose_name_plural': 'دیدگاه آموزش ها'},
        ),
    ]
