# Generated by Django 3.1.7 on 2021-03-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_tutotial_category_tutorialcomment_verbost_name_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='confirm_status',
            field=models.IntegerField(choices=[(-1, 'عدم تایید'), (0, 'در انتظار تایید'), (1, 'تایید شده')], default=0, verbose_name='وضعیت تایید'),
        ),
    ]
