# Generated by Django 3.1.7 on 2021-03-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_tutorial_category_relation_blank_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='down_votes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='امتیاز منفی'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='لایک ها'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='total_views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='بازدید کل'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='up_votes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='امتیاز مثبت'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='user_views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='بازدید کاربران'),
        ),
    ]
