# Generated by Django 3.1.7 on 2021-03-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_tutorial_integerfields_default_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='short_description',
            field=models.TextField(max_length=250, verbose_name='توضیح کوتاه'),
        ),
    ]
