# Generated by Django 3.1.7 on 2021-03-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_tutorial_shrotdescription_textfileld'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcomment',
            old_name='down_votes',
            new_name='down_votes_count',
        ),
        migrations.RenameField(
            model_name='tutorialcomment',
            old_name='likes',
            new_name='likes_count',
        ),
        migrations.RenameField(
            model_name='tutorialcomment',
            old_name='up_votes',
            new_name='up_votes_count',
        ),
    ]
