# Generated by Django 3.1.7 on 2021-03-28 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_tutorialcomment_user_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialtag',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='learning.tutorial', verbose_name='آموزش'),
        ),
    ]
