# Generated by Django 3.1.7 on 2021-03-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_tutorial_tutorialtag_relatedname_fixed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialtag',
            options={'verbose_name': 'کلیدواژه', 'verbose_name_plural': 'کلیدواژه ها'},
        ),
    ]
