# Generated by Django 3.1.7 on 2021-03-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_tutorialtag_verbose_name_verbose_name_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcomment',
            name='confirm_status',
            field=models.IntegerField(choices=[(0, 'در انتظار تایید'), (-1, 'عدم تایید'), (1, 'تایید شده')], default=0, verbose_name='وضعیت تایید'),
        ),
        migrations.AlterField(
            model_name='tutorialcomment',
            name='down_votes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='امتیاز منفی'),
        ),
        migrations.AlterField(
            model_name='tutorialcomment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='لایک ها'),
        ),
        migrations.AlterField(
            model_name='tutorialcomment',
            name='up_votes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='امتیاز مثبت'),
        ),
    ]
