# Generated by Django 3.1.7 on 2021-03-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_tutorialcomment_integerfields_default_zero_confirmstatus_null_blank_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcomment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='ویرایش شده'),
        ),
    ]
