# Generated by Django 3.1.7 on 2021-03-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_tutorialcomment_isedited_default_false'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='comments',
        ),
    ]
