# Generated by Django 3.1.7 on 2021-03-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_tutorialcomment_user_trutorial_relatednames_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_grade',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_category', to='learning.category', verbose_name='پایه والد'),
        ),
    ]
