# Generated by Django 3.1.7 on 2021-04-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_category_child_category_changed_child_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(default='default/learning/tutorial-image.png', upload_to='images/tutorial_thumbnails', verbose_name='تصویر'),
        ),
    ]
