# Generated by Django 3.1.7 on 2021-04-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_tutorial_tutorialcomment_ordering_specified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='last_edit_date',
            field=models.DateField(blank=True, null=True, verbose_name='زمان آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='tutorialcomment',
            name='last_edit_date',
            field=models.DateField(blank=True, null=True, verbose_name='زمان آخرین ویرایش'),
        ),
    ]
