# Generated by Django 3.1.7 on 2021-04-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_tutorial_tutorialcomment_lasteditdate_nullable_True'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='ویرایش شده'),
        ),
    ]
