# Generated by Django 3.1.7 on 2021-04-27 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0024_tutorial_tutorialcomment_confirmstatus_integerchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='tutorialcomment',
            name='tutorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='learning.tutorial', verbose_name='آموزش'),
        ),
        migrations.AlterField(
            model_name='tutorialcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
