# Generated by Django 3.1.7 on 2021-04-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_user_and_tutorial_relations_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcommentdownvote',
            name='coin',
            field=models.IntegerField(verbose_name='سکه'),
        ),
        migrations.AlterField(
            model_name='tutorialcommentdownvote',
            name='score',
            field=models.IntegerField(verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='tutorialdownvote',
            name='coin',
            field=models.IntegerField(verbose_name='سکه'),
        ),
        migrations.AlterField(
            model_name='tutorialdownvote',
            name='score',
            field=models.IntegerField(verbose_name='امتیاز'),
        ),
    ]
