# Generated by Django 3.1.7 on 2021-05-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_tutorialdownvote_tutorialcommentdownvote_score_coin_integer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcommentdownvote',
            old_name='TutorialComment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='tutorialcommentlike',
            old_name='TutorialComment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='tutorialcommentupvote',
            old_name='TutorialComment',
            new_name='comment',
        ),
    ]
