# Generated by Django 3.1.7 on 2021-05-03 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0027_tutorial_comment_user_relations_comment_foreignkey_changed_to_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialcomment',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='tutorialcomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tutorialcomment',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='tutorialcomment',
            name='down_voters',
            field=models.ManyToManyField(related_name='down_voted_tutorial_commens', through='learning.TutorialCommentDownVote', to=settings.AUTH_USER_MODEL, verbose_name='امتیاز منفی دیدگاه ها'),
        ),
        migrations.AddField(
            model_name='tutorialcomment',
            name='likers',
            field=models.ManyToManyField(related_name='liked_tutorial_comments', through='learning.TutorialCommentLike', to=settings.AUTH_USER_MODEL, verbose_name='لایک دیدگاه ها'),
        ),
        migrations.AddField(
            model_name='tutorialcomment',
            name='up_voters',
            field=models.ManyToManyField(related_name='up_voted_tutorial_comments', through='learning.TutorialCommentUpVote', to=settings.AUTH_USER_MODEL, verbose_name='امتیاز مثبت دیدگاه ها'),
        ),
        migrations.AlterField(
            model_name='tutorialcommentdownvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='down_votes', to='learning.tutorialcomment', verbose_name='نظر آموزش'),
        ),
        migrations.AlterField(
            model_name='tutorialcommentdownvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_comment_down_votes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='tutorialcommentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='learning.tutorialcomment', verbose_name='نظر آموزش'),
        ),
        migrations.AlterField(
            model_name='tutorialcommentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='tutorialcommentupvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_votes', to='learning.tutorialcomment', verbose_name='نظر آموزش'),
        ),
        migrations.AlterField(
            model_name='tutorialcommentupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_comment_up_votes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
