# Generated by Django 3.1.7 on 2021-05-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0029_tutorial_tutorialrelations_relatedname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='total_views_count',
        ),
    ]
