# Generated by Django 3.2.3 on 2021-05-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0032_score_coin_field_type_integerfield_default_0'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialcomment',
            options={'ordering': ('-create_date',), 'permissions': (('confirm_disprove_tutorialcomment', 'تایید/رد نظرات'),), 'verbose_name': 'دیدگاه آموزش', 'verbose_name_plural': 'دیدگاه آموزش ها'},
        ),
    ]
