# Generated by Django 3.2.3 on 2021-05-18 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0034_tutorial_confirm_disprove_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_categories', to='learning.category', verbose_name='دسته بندی والد'),
        ),
    ]
