# Generated by Django 3.2.3 on 2021-05-22 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0035_category_parentcategory_verbosename_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcommentdownvote',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
        ),
        migrations.AddField(
            model_name='tutorialcommentlike',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
        ),
        migrations.AddField(
            model_name='tutorialcommentupvote',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
        ),
        migrations.AddField(
            model_name='tutorialdownvote',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
        ),
        migrations.AddField(
            model_name='tutoriallike',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
        ),
        migrations.AddField(
            model_name='tutorialupvote',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
        ),
        migrations.AddField(
            model_name='tutorialview',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
        ),
    ]
