# Generated by Django 3.2.3 on 2021-06-12 19:31

from django.db import migrations
import django_bleach.models
import utilities.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0036_score_coin_models_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='body',
            field=utilities.models.fields.BleachField(verbose_name='بدنه'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='short_description',
            field=utilities.models.fields.BleachField(max_length=250, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='tutorialcomment',
            name='body',
            field=django_bleach.models.BleachField(max_length=500, verbose_name='بدنه'),
        ),
    ]
