# Generated by Django 3.2.4 on 2021-06-13 13:10

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0038_tutorialcomment_body_customized_bleachfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default/learning/tutorial-image.png', force_format='JPEG', keep_meta=True, quality=72, size=[960, 540], upload_to='images/tutorial_thumbnails', verbose_name='تصویر'),
        ),
    ]
